# ruff: noqa: INP001
"""CocoIndex pipeline template.

Auto-generated by @pi-unipi/cocoindex — customize as needed.
Requires cocoindex >= 1.0.

This file is a valid, lintable Python module. At scaffold time, the
PROJECT_BASENAME and PROJECT_DIR lines are replaced with hardcoded values.
For local testing, set COCO_PROJECT_BASENAME and COCO_PROJECT_DIR env vars.
"""

import os
import pathlib
import subprocess
from collections.abc import AsyncIterator
from dataclasses import dataclass

import cocoindex as coco
from cocoindex.connectors import lancedb, localfs
from cocoindex.resources.file import PatternFilePathMatcher

# ── Template Configuration (replaced at scaffold time) ───
PROJECT_BASENAME = os.environ.get("COCO_PROJECT_BASENAME", "project")
PROJECT_DIR = os.environ.get("COCO_PROJECT_DIR", str(pathlib.Path.cwd()))

# ── Configuration ────────────────────────────────────
PROJECT_ROOT = os.environ.get("PROJECT_ROOT", PROJECT_DIR)
# Safety limit for huge generated/lock files. Set COCO_MAX_FILE_CHARS=0 to disable.
MAX_FILE_CHARS = int(os.environ.get("COCO_MAX_FILE_CHARS", "200000"))

# ── LanceDB context key ──────────────────────────────
db_key = coco.ContextKey(f"lancedb/{PROJECT_BASENAME}")


# ── Default excluded patterns ────────────────────────
# Tier 1: static exclusion list covering common ecosystems
DEFAULT_EXCLUDED_PATTERNS: list[str] = [
    # Node / JS
    "**/node_modules/**",
    "**/.git/**",
    "**/dist/**",
    "**/build/**",
    "**/.next/**",
    "**/__pycache__/**",
    "**/coverage/**",
    "**/.turbo/**",
    "**/.cache/**",
    "**/.unipi/**",
    "**/*.min.js",
    "**/bundled.js",
    "**/bundle.js",
    "**/*bundle*.js",
    "**/package-lock.json",
    "**/pnpm-lock.yaml",
    "**/yarn.lock",
    # Python
    "**/.venv/**",
    "**/venv/**",
    "**/.nox/**",
    "**/.tox/**",
    "**/*.egg-info/**",
    "**/.mypy_cache/**",
    "**/.pytest_cache/**",
    "**/.ruff_cache/**",
    "**/.pytype/**",
    "**/.pyre/**",
    # Rust
    "**/target/**",
    # Go
    "**/vendor/**",
    # Java / Kotlin
    "**/.gradle/**",
    "**/out/**",
    # OS artifacts
    "**/.DS_Store",
    "**/Thumbs.db",
    # Environment files
    "**/.env",
    "**/.env.local",
]


# ── Tier 2: CACHEDIR.TAG detection ───────────────────
CACHEDIR_SIGNATURE = b"Signature: 8a477f597d28d172789f06886806bc55"
_cachedir_cache: dict[str, bool] = {}


def is_cache_dir(dir_path: str) -> bool:
    """Check if a directory has a valid CACHEDIR.TAG."""
    tag = pathlib.Path(dir_path) / "CACHEDIR.TAG"
    try:
        with open(tag, "rb") as f:
            return f.read(43) == CACHEDIR_SIGNATURE
    except OSError:
        return False


def has_cache_ancestor(file_path: str, root: str) -> bool:
    """Check if any ancestor directory (between root and file) is a cache dir."""
    rel = pathlib.Path(file_path).relative_to(root)
    for parent in rel.parents:
        if parent == pathlib.Path():
            continue
        dir_path = str(pathlib.Path(root) / parent)
        if dir_path not in _cachedir_cache:
            _cachedir_cache[dir_path] = is_cache_dir(dir_path)
        if _cachedir_cache[dir_path]:
            return True
    return False


# ── Tier 3: Git-aware exclusion ──────────────────────
def get_git_ignored_files(
    file_paths: list[str],
    cwd: str,
    batch_size: int = 1000,
) -> set[str]:
    """Ask git which files are ignored.

    Uses git check-ignore with all configured ignore sources
    (core.excludesFile, .gitignore, info/exclude).
    Returns set of ignored relative paths.
    """
    if not file_paths:
        return set()
    ignored: set[str] = set()
    for i in range(0, len(file_paths), batch_size):
        batch = file_paths[i : i + batch_size]
        try:
            result = subprocess.run(
                ["git", "check-ignore", "--stdin", "-z"],  # noqa: S607
                input="\0".join(batch),
                capture_output=True,
                text=True,
                cwd=cwd,
                timeout=30,
                check=False,
            )
            if result.returncode == 128:  # noqa: PLR2004
                # Not a git repo — skip git-based filtering entirely
                return set()
            ignored.update(p for p in result.stdout.split("\0") if p)
        except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
            # git not installed or timed out — degrade gracefully
            return set()
    return ignored


# ── Tier 4: User-global excludes ─────────────────────
def load_user_excludes() -> list[str]:
    """Load patterns from ~/.unipi/cocoindex/excludes (one glob per line).

    Lines starting with # are comments. Empty lines are skipped.
    """
    excludes_file = pathlib.Path.home() / ".unipi" / "cocoindex" / "excludes"
    if not excludes_file.exists():
        return []
    patterns: list[str] = []
    for raw_line in excludes_file.read_text().splitlines():
        stripped = raw_line.strip()
        if stripped and not stripped.startswith("#"):
            patterns.append(stripped)
    return patterns


# ── Included file patterns ───────────────────────────
INCLUDED_PATTERNS: list[str] = [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "**/*.py",
    "**/*.rs",
    "**/*.go",
    "**/*.md",
    "**/*.txt",
    "**/*.json",
    "**/*.yaml",
    "**/*.yml",
    "**/*.sh",
    "**/*.bash",
]


# ── Environment setup (async lifespan) ───────────────
@coco.lifespan
async def coco_lifespan(builder: coco.EnvironmentBuilder) -> AsyncIterator[None]:
    """Configure environment: DB path + LanceDB connection."""
    builder.settings.db_path = pathlib.Path(__file__).parent / "cocoindex.db"

    db_path = pathlib.Path(__file__).parent / ".lancedb"
    conn = await lancedb.connect_async(str(db_path))
    builder.provide(db_key, conn)

    yield


# ── Row type for LanceDB ─────────────────────────────
@dataclass
class IndexRow:
    """A single indexed chunk stored in LanceDB."""

    path: str
    chunk_index: int
    content: str


# ── Chunking function (memoized) ─────────────────────
@coco.fn
async def chunk_text(
    content: str,
    *,
    chunk_size: int = 1500,
    chunk_overlap: int = 200,
) -> list[tuple[int, str]]:
    """Split text into overlapping chunks."""
    if not content.strip():
        return []

    chunks: list[tuple[int, str]] = []
    start = 0
    idx = 0
    while start < len(content):
        end = min(start + chunk_size, len(content))
        chunk = content[start:end].strip()
        if chunk:
            chunks.append((idx, chunk))
            idx += 1
        start += chunk_size - chunk_overlap
        start = max(start, 0)

    return chunks


# ── Process a single file ────────────────────────────
@coco.fn
async def process_file(
    file: localfs.File,
    table: lancedb.TableTarget,
) -> None:
    """Read a file, chunk it, and declare rows in LanceDB."""
    try:
        content = await file.read_text()
    except Exception:  # noqa: BLE001
        return

    if not content.strip():
        return
    if MAX_FILE_CHARS > 0 and len(content) > MAX_FILE_CHARS:
        return

    relative = file.file_path.path.as_posix()
    chunks = await chunk_text(content)

    for chunk_idx, text in chunks:
        table.declare_row(
            row=IndexRow(
                path=relative,
                chunk_index=chunk_idx,
                content=text,
            ),
        )


# ── Main app function ────────────────────────────────
@coco.fn
async def app_main() -> None:
    """Walk project files, chunk, and store in LanceDB.

    Applies 4 tiers of exclusion:
      1. Static pattern list (ecosystem defaults)
      2. CACHEDIR.TAG detection (uv, cargo, gradle, etc.)
      3. Git-aware ignore (respects .gitignore, core.excludesFile, etc.)
      4. User-global excludes (~/.unipi/cocoindex/excludes)
    """
    project_root = pathlib.Path(PROJECT_ROOT)

    # 1) Declare LanceDB table target
    table_schema = await lancedb.TableSchema.from_class(
        IndexRow,
        primary_key=["path", "chunk_index"],
    )

    target = await coco.mount_target(
        lancedb.table_target(
            db_key,
            f"{PROJECT_BASENAME}_index",
            table_schema,
        ),
    )
    table = lancedb.TableTarget(target, table_schema)

    # Tier 4: merge user-global excludes with defaults
    user_excludes = load_user_excludes()
    all_excluded = DEFAULT_EXCLUDED_PATTERNS + user_excludes

    # 2) Walk project files (Tier 1 + 4: pattern-based filtering)
    walker = localfs.walk_dir(
        project_root,
        recursive=True,
        path_matcher=PatternFilePathMatcher(
            included_patterns=INCLUDED_PATTERNS,
            excluded_patterns=all_excluded,
        ),
    )

    # 3) Collect files, applying Tier 2 (CACHEDIR.TAG) filter
    candidates: list[tuple[object, str]] = []
    async for file in walker:
        rel = file.file_path.path.as_posix()
        abs_path = str(project_root / rel)
        if has_cache_ancestor(abs_path, str(project_root)):
            continue
        candidates.append((file, rel))

    # 4) Tier 3: batch git check-ignore
    all_paths = [rel for _, rel in candidates]
    git_ignored = get_git_ignored_files(all_paths, str(project_root))

    # 5) Process non-ignored files
    for file, rel in candidates:
        if rel in git_ignored:
            continue
        await coco.mount(
            coco.component_subpath("process", rel),
            process_file,
            file,
            table,
        )


# ── App instance (required by CLI) ───────────────────
app = coco.App(
    coco.AppConfig(name=f"local_{PROJECT_BASENAME}"),
    app_main,
)
